# Generated by Django 4.1.4 on 2022-12-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='序列号')),
                ('vendor', models.CharField(max_length=32, verbose_name='厂商')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='虚拟化')),
                ('group', models.CharField(choices=[('0', '一组'), ('1', '二组'), ('3', '三组')], max_length=32, verbose_name='运维组')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
